name = "FPS BOOM!"
author = "LowOnEspresso"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9789f327e45b5b40476dc51ef12b0cbc7ff40eea9532c528bc33bcf6ced1f48c"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
