name = "FPS BOOM!"
author = "LowOnEspresso"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3e3ac4b10493a0616b9caefa9197cd59a086fa00655ca4994f1a2d431b322bd"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
