name = "FPS BOOM!"
author = "LowOnEspresso"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99ca3fb65bb50a99f3c89cfcf2d031b17f6d662ec948da63e7223f2001e6f7ff"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
