name = "FPS BOOM!"
author = "LowOnEspresso"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be13a77808e6543948b73b6521efc9356f881e140f60a890cf2a4722b4da95a4"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
