name = "FPS BOOM!"
author = "LowOnEspresso"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2acedf6e41119c2137d1e85bad296df93b3f555822dfc212fc2d893e1f61f536"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
