name = "FPS BOOM!"
author = "LowOnEspresso"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ffa36a9946840c261a94aa70ee80a6c5456502c9de7ce0ec30d21d32f4fb500"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
