name = "FPS BOOM!"
author = "LowOnEspresso"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36cc4a7929820a767a735f42a5878c910848cb134d41d819ca7724179205cc32"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
